elvis/elvis/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings

import os

from rest_framework.urlpatterns import format_suffix_patterns

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from elvis.views.main import home
from elvis.views.main import upload
from elvis.views.main import save_downloads
from elvis.views.main import user_profiles, user_view
from elvis.views.main import projects_list, project_view, project_participants, project_discussions, discussion_view
from elvis.views.main import search_view, queries
from elvis.views.main import corpora_list, corpora_list_min, corpus_view
from elvis.views.main import composer_list, composer_list_min, composer_view
from elvis.views.main import piece_list, piece_view
from elvis.views.main import movement_list, movement_view
from elvis.views.main import download_list

from elvis.views.search import search
from elvis.views.search import search_results

from elvis.views.download import DownloadList, DownloadDetail
from elvis.views.piece import PieceList, PieceDetail
from elvis.views.corpus import CorpusList, CorpusDetail
from elvis.views.user import UserList, UserDetail
from elvis.views.userprofile import UserProfileList, UserProfileDetail
from elvis.views.movement import MovementList, MovementDetail
from elvis.views.composer import ComposerList, ComposerDetail
from elvis.views.tag import TagList, TagDetail
from elvis.views.attachment import AttachmentList, AttachmentDetail

from elvis.views.forms import create_composer, create_corpus, create_corpus_large, create_project
from elvis.views.forms import create_piece, create_movement
from elvis.views.forms import upload_file, delete_model
from elvis.views.forms import download_piece, save_piece, download_movement, save_movement


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

media_path = os.path.realpath('media/attachments/')

urlpatterns = []

urlpatterns += format_suffix_patterns(
    patterns('',
        url(r'^$', home, name='home'),
        
        #url(r'^search/', include('haystack.urls')),

        url(r'^users/$', UserList.as_view(), name="user-list"),
        url(r'^user/(?P<pk>[0-9]+)/$', UserDetail.as_view(), name="user-detail"),

        #url(r'^userprofiles/$', UserProfileList.as_view(), name="userprofile-list"),
        url(r'^userprofiles/$', user_profiles, name="userprofile-list"),
        #url(r'^userprofiles/(?P<pk>[0-9]+)/$', UserProfileDetail.as_view(), name="userprofile-detail"),
        url(r'^userprofiles/(?P<pk>[0-9]+)/$', user_view, name="userprofile-detail"),

        url(r'^projects/$', projects_list, name="projects-list"),
        url(r'^projects/(?P<pk>[0-9]+)/$', project_view, name="project-detail"),
        url(r'^projects/(?P<pk>[0-9]+)/participants$', project_participants, name="project-participants"),
        url(r'^projects/(?P<pk>[0-9]+)/discussions$', project_discussions, name="project-discussions"),
        url(r'^projects/(?P<pk>[0-9]+)/discussions/(?P<did>[0-9]+)$', discussion_view, name="project-discussions"),

        #url(r'^pieces/$', PieceList.as_view(), name="piece-list"),
        #url(r'^piece/(?P<pk>[0-9]+)/$', PieceDetail.as_view(), name="piece-detail"),
        #url(r'^corpora/$', CorpusList.as_view(), name="corpus-list"),
        #url(r'^corpus/(?P<pk>[0-9]+)/$', CorpusDetail.as_view(), name="corpus-detail"),
        #url(r'^composers/$', ComposerList.as_view(), name="composer-list"),
        #url(r'^composer/(?P<pk>[0-9]+)/$', ComposerDetail.as_view(), name="composer-detail"),
        #url(r'^movements/$', MovementList.as_view(), name="movement-list"),
        #url(r'^movement/(?P<pk>[0-9]+)/$', MovementDetail.as_view(), name="movement-detail"),

        url(r'^pieces/$', piece_list, name="piece-list"),
        url(r'^pieces/(?P<pk>[0-9]+)/$', piece_view, name="piece-detail"),
        url(r'^corpora/$', corpora_list, name="corpus-list"),
        url(r'^corporamin/$', corpora_list_min, name="corpus-list-min"),
        url(r'^corpora/(?P<pk>[0-9]+)/$', corpus_view, name="corpus-detail"),
        url(r'^composers/$', composer_list, name="composer-list"),
        url(r'^composersmin/$', composer_list_min, name="composer-list-min"),
        url(r'^composers/(?P<pk>[0-9]+)/$', composer_view, name="composer-detail"),
        url(r'^movements/$', movement_list, name="movement-list"),
        url(r'^movements/(?P<pk>[0-9]+)/$', movement_view, name="movement-detail"),

        url(r'^upload/corpus/$', create_corpus_large, name="create-corpus-large"),
        url(r'^upload/piece/$', create_piece, name="create-piece"),
        url(r'^upload/movement/$', create_movement, name="create-movement"),
        url(r'^upload/project/$', create_project, name="create-project"),
        
        url(r'^tags/$', TagList.as_view(), name="tag-list"),
        url(r'^tag/(?P<pk>[0-9]+)/$', TagDetail.as_view(), name="tag-detail"),

        url(r'^search_results/$', search_view, name="search_results"),
        url(r'^upload/$', upload_file, name="upload"),

        url(r'^queries/$', queries, name="queries"),

        url(r'^addcomposer/$', create_composer, name="create-composer"),
        url(r'^addcorpus/$', create_corpus, name="create-corpus"),

        url(r'^(?P<entity>[a-z_]+)/(?P<pk>[0-9]+)/delete/', delete_model, name="delete-model"),

        url(r'^downloads/$', download_list, name="download-list"),
        #url(r'^downloads/$', DownloadList.as_view(), name="download-list"),
        #url(r'^download/(?P<pk>[0-9]+)/$', DownloadDetail.as_view(), name="download-detail"),
        #url(r'^download/$', save_downloads, name="save_downloads"),
        #url(r'^download/$', DownloadList.as_view(), name="download-list"),
        url(r'^pieces/(?P<pk>[0-9]+)/download/$', download_piece, name="download-piece"),
        url(r'^pieces/(?P<pk>[0-9]+)/save/$', save_piece, name="save-piece"),
        url(r'^movements/(?P<pk>[0-9]+)/download/$', download_movement, name="download-movement"),
        url(r'^movements/(?P<pk>[0-9]+)/save/$', save_movement, name="save-movement"),
        
        url(r'^attachments/$', AttachmentList.as_view(), name="attachment-list"),
        url(r'^attachment/(?P<pk>[0-9]+)/$', AttachmentDetail.as_view(), name="attachment-detail"),

        (r'^media/attachments/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )
)

# Serving static files
#urlpatterns += staticfiles_urlpatterns()

# Media stuff
urlpatterns += patterns('', 
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += staticfiles_urlpatterns()

# Only add admin if it's enabled
if 'django.contrib.admin' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^admin/', include(admin.site.urls)),
    )


# For serving stuff under MEDIA_ROOT in debug mode only
# if settings.DEBUG:
#     urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elvis/elvis/models/attachment.py
import os
import shutil
import random
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

from datetime import datetime

class Attachment(models.Model):
    """
        IMPORTANT: This model will store its attachments in a
        random folder structure. This is to prevent the webapp from
        putting too many files in a single directory.

        The format is:

        attachments/[XX]/[XX]/[PK]

        Where XXXX represents a 2-digit number taken from a subset of the PK
        and [PK] represents the primary key of the attachment padded to 15 zeros.

        This means that you MUST save a blank copy of this model BEFORE
        attempting to attach a file. If not, self.pk will not be set and all
        kinds of weirdness will take place.
    """

    @property
    def attachment_path(self):
        return os.path.join(settings.MEDIA_ROOT,
                            "attachments",
                            "{0:0>2}".format(str(self.pk)[0:2]),
                            "{0:0>2}".format(str(self.pk)[-2:]),
                            "{0:0>15}".format(self.pk))

    def upload_path(self, filename):
        return os.path.join(self.attachment_path, filename)

    old_id = models.IntegerField(null=True, blank=True, db_index=True)
    attachment = models.FileField(upload_to=upload_path, null=True, max_length=512)
    uploader = models.ForeignKey(User, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # created = models.DateTimeField(default=datetime.now, blank=True)
    # updated = models.DateTimeField(default=datetime.now, blank=True)

    def save(self, *args, **kwargs):
        super(Attachment, self).save(*args, **kwargs)
        if not os.path.exists(self.attachment_path):
            os.makedirs(self.attachment_path)

    def delete(self, *args, **kwargs):
        if os.path.exists(self.attachment_path):
            shutil.rmtree(self.attachment_path)
        super(Attachment, self).delete(*args, **kwargs)

    def __unicode__(self):
        return u"{0}".format(self.attachment)

    class Meta:
        app_label = "elvis"

elvis/elvis/models/comment.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Comment(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    text = models.TextField()
    user = models.ForeignKey(User)
    discussion = models.ForeignKey("elvis.Discussion")

    created = models.DateTimeField(default=datetime.now, blank=True)

    def __unicode__(self):
        return u"{0}".format(self.text)

    class Meta:
        app_label = "elvis"

elvis/elvis/models/composer.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class Composer(models.Model):

    def picture_path(self):
        return '/'.join('photos/composers', self.name.__unicode__)

    old_id = models.IntegerField(db_index=True, blank=True, null=True)
    name = models.CharField(max_length=255)
    birth_date = models.DateField(blank=True, null=True)
    death_date = models.DateField(blank=True, null=True)
    picture = models.ImageField(upload_to=picture_path, null=True)
    number_of_queries = models.IntegerField(blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # created = models.DateTimeField(default=datetime.now, blank=True)
    # updated = models.DateTimeField(default=datetime.now, blank=True)

    def __unicode__(self):
        return u"{0}".format(self.name)

    class Meta:
        app_label = "elvis"

elvis/elvis/models/corpus.py
from django.db import models
from django.contrib.auth.models import User


class Corpus(models.Model):

    def picture_path(self):
        return '/'.join('photos/corpora', self.title.__unicode__)

    old_id = models.IntegerField(db_index=True, blank=True, null=True)
    creator = models.ForeignKey(User)
    title = models.CharField(max_length=255, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    number_of_queries = models.IntegerField(blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # created = models.DateTimeField(default=datetime.now, blank=True)
    # updated = models.DateTimeField(default=datetime.now, blank=True)

    picture = models.ImageField(upload_to=picture_path, null=True)

    def __unicode__(self):
        return u"{0}".format(self.title)

    class Meta:
        verbose_name_plural = "corpora"
        app_label = "elvis"

elvis/elvis/models/movement.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime


class Movement(models.Model):
    old_id = models.IntegerField(db_index=True, blank=True, null=True)
    title = models.CharField(max_length=255)
    uploader = models.ForeignKey(User, blank=True, null=True)
    piece = models.ForeignKey("elvis.Piece", blank=True, null=True)
    corpus = models.ForeignKey("elvis.Corpus", blank=True, null=True)
    composer = models.ForeignKey("elvis.Composer", blank=True, null=True)
    date_of_composition = models.DateField(blank=True, null=True)
    number_of_voices = models.IntegerField(blank=True, null=True)
    tags = models.ManyToManyField("elvis.Tag", blank=True, null=True)
    attachments = models.ManyToManyField("elvis.Attachment", blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    number_of_queries = models.IntegerField(blank=True, null=True)
    number_of_downloads = models.IntegerField(blank=True, null=True)

    #created = models.DateTimeField(auto_now_add=True)
    #updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=datetime.now, blank=True)
    updated = models.DateTimeField(default=datetime.now, blank=True)

    def __unicode__(self):
        return u"{0}".format(self.title)

    class Meta:
        app_label = "elvis"

elvis/elvis/forms/entity.py
from django import forms

class ComposerForm(forms.Form):
    name = forms.CharField(max_length=255)
    birth_date = forms.CharField(required=False)
    death_date = forms.CharField(required=False)
    picture = forms.ImageField(required=False)

    def validate_date(self, birth, death): return birth < death 

class CorpusForm(forms.Form):
	title = forms.CharField(max_length=255)
	comment = forms.CharField(widget=forms.Textarea, required=False)
	picture = forms.ImageField(required=False)

class PieceForm(forms.Form):
    title = forms.CharField(max_length=255)
    composer = forms.CharField(max_length=255)
    corpus = forms.CharField(max_length=255)
    date_of_composition = forms.CharField(required=False)
    number_of_voices = forms.IntegerField(required=False)
    tags = forms.CharField(widget=forms.Textarea)
    comment = forms.CharField(widget=forms.Textarea, required=False)
    attachment = forms.FileField(required=False)
    description = forms.CharField(widget=forms.Textarea, required=False)

class AttachmentForm(forms.Form):
	title = forms.CharField(max_length=255)
	description = forms.CharField(widget=forms.Textarea, required=False)

class MovementForm(forms.Form):
    title = forms.CharField(max_length=255)
    piece = forms.CharField(max_length=255)
    attachment = forms.FileField()
    composer = forms.CharField(max_length=255)
    corpus = forms.CharField(max_length=255)
    date_of_composition = forms.CharField(required=False)
    number_of_voices = forms.IntegerField(required=False)
    tags = forms.CharField(widget=forms.Textarea)
    comment = forms.CharField(widget=forms.Textarea, required=False)
    description = forms.CharField(max_length=255, required=False)

elvis/elvis/forms/project.py
from django import forms

class ProjectForm(forms.Form):
	name = forms.CharField(max_length=255)
	description = forms.CharField(widget=forms.Textarea, required=False)
	users = forms.CharField(widget=forms.Textarea, required=False)

class DiscussionForm(forms.Form):
	name = forms.CharField(max_length=255)
	comment = forms.CharField(widget=forms.Textarea)
	#project = foreign key
	#user = current user

class CommentForm(forms.Form):
	name = forms.CharField(max_length=255, required=False)
	text = forms.CharField(widget=forms.Textarea)
    #user = current user
    #discussion = current discussion

class TodoForm(forms.Form):
	name = forms.CharField(max_length=255, required=False)
	description = forms.CharField(widget=forms.Textarea)
	due_date = forms.DateField(required=False)
	#project = current project
	#assigned_to = foreign key user -- need some kind of interaction with notification form? 

elvis/elvis/forms/user.py
from django import forms

class UserForm(forms.Form):
	first_name = forms.CharField(max_length=255)
	last_name = forms.CharField(max_length=255)
	# Username can't already be taken 
	username = forms.CharField()
	# Password must be strong enough
	password = forms.CharField()
	# Email can't already be in use 
	email = forms.EmailField()

	picture = forms.ImageField(required=False)


'''
Used to invite user to website, project
'''
class InviteUserForm(forms.Form):
	email = forms.EmailField()
	subject = forms.CharField(max_length=255)
	message = forms.CharField(widget=forms.Textarea)

elvis/elvis/views/attachment.py
from rest_framework import generics
from rest_framework import permissions
from rest_framework.renderers import JSONRenderer, JSONPRenderer

from elvis.renderers.custom_html_renderer import CustomHTMLRenderer
from elvis.serializers.attachment import AttachmentSerializer
from elvis.models.attachment import Attachment


'''
class AttachmentListHTMLRenderer(CustomHTMLRenderer):
    template_name = "attachment/attachment_list.html"


class AttachmentDetailHTMLRenderer(CustomHTMLRenderer):
    template_name = "attachment/attachment_detail.html"
'''


class AttachmentList(generics.ListCreateAPIView):
    model = Attachment
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = AttachmentSerializer
    #renderer_classes = (JSONRenderer, JSONPRenderer, AttachmentListHTMLRenderer)


class AttachmentDetail(generics.RetrieveUpdateDestroyAPIView):
    model = Attachment
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    serializer_class = AttachmentSerializer
    #renderer_classes = (JSONRenderer, JSONPRenderer, AttachmentDetailHTMLRenderer)

elvis/elvis/templates/forms/composer.html
<style type="text/css">

body {
	background-color:#FFF8DC;
	font-family:sans-serif;
}
 
#header {
	background-color:#ADD8E6;
}
#header-error {
	background-color:#CD5C5C;
}
.error {
	color:#FFFFFF;
	font-weight:bold;
	text-align:center;
	font-size:.8em;
	padding-top:10px;
	padding-bottom:10px;
}
.instruction {
	text-align:center;
	font-weight:bold;
	font-size:.8em;
	padding-top:10px;
	padding-bottom:10px;
}

#id_name, #id_birth_date, #id_death_date {
	border:0;
	background:none;
	outline:0;
}
#id_name {
	font-size:1.5em;
}
#id_birth_date, #id_death_date {
	font-size:.9em;
}

#date-examples {
	font-size:.6em;
}

#composer-name, #composer-dates, #composer-picture {
	margin-left:20px;
	margin-right:20px;
}
#composer-name, #composer-name-error {
	border-bottom:solid;
	border-width:1px;
}
#composer-name-error, #bd-error {
	font-color:#CD5C5C;
}
#bd, #bd-error {
	border-bottom:dotted;
	border-width:1px;
}
.submit {
	text-align:center;
}

.default-pic {
	height:50px;
	width:70px;
	overflow:hidden;
}

</style>

<body>
<div class="container-fluid">

{% if form.errors %}
	<div class="row-fluid" id="header-error">
		<h4 class="error">Please correct the error{{ form.errors|pluralize }} below.</h4>
	</div>
{% else %}
	<div class="row-fluid" id="header">
		<h4 class="instruction">ADD A COMPOSER</h4>
	</div>
{% endif %}

<form action="" method="post">
    <div class="row-fluid" id="composer-name">{{ form.name }}</div>
    <br>
    <div class="row-fluid" id="composer-dates">
    	<table>
    		<tr> <td id="bd">{{ form.birth_date}}</td>  <td id="bd">{{ form.death_date }}</td> </tr>
    		<tr><td id="date-examples">ex: 09-12-13</td></tr>
    	</table>
    </div>
    <br><br>
    <div class="row-fluid" id="composer-picture">
    	<img class="default-pic" src="{{MEDIA_URL}}generics/composers/{{picture}}"/>
    	{{form.picture}}
    </div>

    <br><br>

{% if form.errors %} {{ form.errors }}
<div class="submit">
    {% csrf_token %}
    <button type="submit" value="Download" class="btn btn-primary">Add composer</button>
	</div>
{% else %}
    <div class="submit">
    {% csrf_token %}
    <button type="submit" value="Download" class="btn btn-primary">Add composer</button>
	</div>
{% endif %}
</form>

</div>

</body>

elvis/elvis/templates/forms/corpus.html
<style type="text/css">

body {
	background-color:#FFF8DC;
	font-family:sans-serif;
}

#header {
	background-color:#ADD8E6;
}
#header-error {
	background-color:#CD5C5C;
}
.error {
	color:#FFFFFF;
	font-weight:bold;
	text-align:center;
	font-size:.8em;
	padding-top:10px;
	padding-bottom:10px;
}
.instruction {
	text-align:center;
	font-weight:bold;
	font-size:.8em;
	padding-top:10px;
	padding-bottom:10px;
}

#id_title, #id_comment {
	border:0;
	background:none;
	outline:0;
}
#id_title {
	font-size:1.5em;
}
#id_comment {
	font-size:1em;
}

#corpus-title, #corpus-comment, #corpus-picture {
	margin-left:20px;
	margin-right:20px;
}
#corpus-title {
	border-bottom:solid;
	border-width:1px;
}

#corpus-comment {
	border:dotted;
	border-width:1px;
}
.submit {
	text-align:center;
}

.default-pic {
	height:50px;
	width:70px;
	overflow:hidden;
}

</style>

<body>
<div class="container-fluid">

{% if form.errors %}
	<div class="row-fluid" id="header-error">
		<h4 class="error">Please correct the error{{ form.errors|pluralize }} below.</h4>
	</div>
{% else %}
	<div class="row-fluid" id="header">
		<h4 class="instruction">ADD A CORPUS</h4>
	</div>
{% endif %}

<form action="" method="post">
    <div class="row-fluid" id="corpus-title">{{ form.title }}</div>
    <br>
    <div class="row-fluid" id="corpus-comment">
    	{{ form.comment }}
    </div>
    <br>
    <div class="row-fluid" id="corpus-picture">
    	<img class="default-pic" src="{{MEDIA_URL}}generics/corpora/{{picture}}"/>
    	{{ form.picture }}
    </div>

    <br><br>

{% if form.errors %} {{ form.errors }}
<div class="submit">
    {% csrf_token %}
    <button type="submit" value="Download" class="btn btn-primary">Add corpus</button>
	</div>
{% else %}
    <div class="submit">
    {% csrf_token %}
    <button type="submit" value="Download" class="btn btn-primary">Add corpus</button>
	</div>
{% endif %}
</form>

</div>

</body>

elvis/elvis/templates/forms/download.html
{% extends "base.html" %}

{% block wrap %}

<style type="text/css">
.download {
	margin-top:40px;
	margin-left:60px;
}
</style>

<div class="download">
<h4>Downloading file...</h4>
</div>

{% endblock %}

elvis/elvis/templates/forms/movement.html
{% extends "forms/upload.html" %}

{% block content %}

<style type="text/css">

#separator-activity {
    border-top:solid;
    border-width:2px;
    border-color:#909090;
    margin-left:40px;
    margin-right:40px;
    background-color:#FFFFFF;
    -moz-box-shadow: 0 0 5px #888;
    -webkit-box-shadow: 0 0 5px#888;
    box-shadow: 0 0 5px #888;
}

#piece-title {
	border-bottom:solid;
	border-width:2px;
}
#piece-composer, #piece-corpus {
	border-bottom:solid;
	border-width:1px;
}
#piece-date {
	border-bottom:dotted;
	border-width:1px;
}
#piece-date-example {
	font-size:.8em;
	color:#6B8E23;
	font-weight:bold;
}

#id_title {
	font-size:1.6em;
	font-weight:bold;
	width:420px;
}

#id_composer, #id_corpus, #id_piece {
	font-size:1.3em;
	width:280px;
}

#id_title, #id_piece, #id_composer, #id_corpus, #id_date_of_composition, #id_comment, #id_description {
	border:0;
	background:none;
	outline:0;
}

#id_number_of_voices {
	width:30px;
	height:30px;
}

#id_tags {
	width:400px;
	height:60px;
	background:none;
}
#id_comment, #id_description {
	width:426px;
	height:120px;
}
#piece-comment {
	border:dotted;
}
#piece-descrip {
	border:dotted;
	border-width:1px;
} 

.num-voices, .tags, #comment, #attachments {
	color:#606060;
	font-weight:bold;
}

.row-fluid {
	margin-left:20px;
}

#voice-info-hide, #tag-info, #file-info {
	font-size:.8em;
}

#save {
	text-align:center;
}
</style>

<script language="javascript"> 
function toggle() {
    var ele = document.getElementById("voice-info");
    var text = document.getElementById("voice-info-hide");
    if(ele.style.display == "block") {
        ele.style.display = "none";
    }
    else {
        text.style.display = "block";
    }
} 
</script>


<div class="container-fluid" id="separator-activity">

{% if form.errors %}
	<h4 class="error">Please correct the error{{ form.errors|pluralize }} below.</h4><br>
{% else %}
	<h4 class="instruction">Add a movement</h4><br>
{% endif %}

<form action="" method="post">
    <div class="row-fluid">
    	<div class="span6" id="piece-title"> {{ form.title }} </div>
    </div>
    <br>
    <div class="row-fluid">
    	<div class="span4" id="piece-composer">{{ form.composer }}</div>
    </div>
    <br>
    <div class="row-fluid" >
    	<div class="span4" id="piece-corpus">{{ form.corpus }}</div>
    </div>
    <br>
    <div class="row-fluid" >
    	<div class="span4" id="piece-corpus">{{ form.piece }}</div>
    </div>
    <br>
    <div class="row-fluid">
    	<div class="span3" id="piece-date">{{ form.date_of_composition }}</div>
    </div>
    <div class="row-fluid">
    	<div class="span3" id="piece-date-example">ex: 09-29-93</div>
    </div>
    <br>
    <div class="row-fluid">
    	<div class="span6" id="piece-voices">
    		<div class="num-voices">Number of voices</div>
    		<div>{{ form.number_of_voices }} <a id="voice-info" href="javascript:toggle();">What is this? </b><i class="icon-chevron-down"></i></a></div>
    		<div id="voice-info-hide" style="display: none">
    			<i>This is the number of distinct polyphonic lines, where applicable (use "0" for solo pieces without distinct voices and for one voice + obbligato accompaniment). Divisi count only if they persist for an entire section, and doubled basslines count as one voice. For complete guidelines please refer to the Data Entry Guidelines.</i>
    		</div>
    	</div>
    </div><br>
    <div class="row-fluid"> <div class="tags">Tags </div></div>
    <div class="row-fluid">
    	<div class="span6" id="piece-tags">{{ form.tags }}</div>
    </div>
    <div class="row-fluid">
    	<div class="span6" id="tag-info">
    	<b>The tags field should always include:</b>
		<i>vocal and/or instrumental genre instrumentation / voices edition (if known) source (if known) language (if texted) sacred/secular (if texted) if applicable, "missing voice(s)" (specify which in comments below)</i>
		</div>
    </div>
    <br>
    <div class="row-fluid">
    	<div class="span4" id="comment">Comments</div>
    </div>
    <div class="row-fluid">
    	<div class="span6" id="piece-comment">{{ form.comment }}</div>
    </div>
    <br>
    <div class="row-fluid" id="attachments"> Attachments </div>
    <div class="row-fluid">
    	<div class="span4" id="piece-attachment">{{ form.attachment }}</div>
    </div>
    <div class="row-fluid">
    	<div class="span6" id="file-info">
    	Files must be less than <b>200 MB.</b>
		Allowed file types: <b>xml mxl krn mei midi mid abc sib mus nwc nwctxt sml ly ily etf pdf nweps mscx mscz ps jpg tiff tif jpeg txt md.</b>
		</div>
    </div><br>
    <div class="row-fluid">
    	<div class="span6" id="piece-descrip">{{ form.description }}</div>
    </div>
    
    <br><br>

    <div class="row-fluid" id="save">
    <button type="submit" value="submit" class="btn btn-success">Save movement </button>
	</div>

</form>
</div>

{% endblock %}

elvis/elvis/templates/forms/save.html
{% extends "base.html" %}

{% block wrap %}

<h4>File saved!</h4>

{% endblock %}

elvis/elvis/templates/forms/success.html
Success!